### ISSUE TITLE
fLib question

### ISSUE THREAD

**Issue by rausch-supola** [acdh-oeaw/vicav-content#21]
@dasch124 @charlymo in this line https://github.com/acdh-oeaw/vicav-content/blob/45f50627cfcb5d7c5fe29ac781bc5a82a703d395/vocabs/fLib.xml#L176
shouldn't the name be "activeParticiple"?

**Comment by dasch124** [comment]
Indeed, well spotted!
Please go ahead and correct it!

From: rausch-supola ***@***.***>
Sent: Monday, December 9, 2024 9:06 AM
To: acdh-oeaw/vicav-content ***@***.***>
Cc: Schopper, Daniel ***@***.***>; Mention ***@***.***>
Subject: [EXT] [acdh-oeaw/vicav-content] fLib question (Issue #21)

External Email: please use links and attachments from trusted sources only


@dasch124<https://github.com/dasch124> @charlymo<https://github.com/charlymo> in this line https://github.com/acdh-oeaw/vicav-content/blob/45f50627cfcb5d7c5fe29ac781bc5a82a703d395/vocabs/fLib.xml#L176
shouldn't the name be "activeParticiple"?

**Comment by rausch-supola** [comment]
done
